PACKAGE_GROUP_audio = " \
  alsa-utils \
  alsa-utils-aplay \
  alsa-utils-amixer \
 "
#  angstrom-zeroconf-audio \

PACKAGE_GROUP_firmware = " \
  kmod \
  marvell-sdio-fw \
  rt73-firmware \
  zd1211-firmware \
  linux-firmware \
 "

PACKAGE_GROUP_kernel_modules = " \
  kernel-module-libertas-sdio \
  kernel-module-usb8xxx \
  kernel-module-mac80211 \
  kernel-module-lib80211 \
 "

PACKAGE_GROUP_gles = " \
 "
#  libgles-omap3 \

PACKAGE_GROUP_tools = " \
  bash \
  bzip2 \
  ckermit \
  devmem2 \
  dhcp-client \
  dosfstools \
  fbgrab \
  fbset \
  fbset-modes \
  i2c-tools \
  mkfs-jffs2 \
  mtd-utils \
  nano \
  ntp ntpdate \
  openssh-misc \
  openssh-scp \
  openssh-ssh \
  omap3-writeprom \
  procps \
  socat \
  strace \
  sudo \
  syslog-ng \
  task-proper-tools \
  u-boot-utils \
  wpa-supplicant \
 "
